<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-08-01 11:05

$extensionPath = t3lib_extMgm::extPath('pnf_capdemat');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_pnfcapdemat_flexform_helper' => $extensionClassesPath . 'class.tx_pnfcapdemat_flexform_helper.php',
	'tx_pnfcapdemat_pi1' => $extensionPath . 'pi1/class.tx_pnfcapdemat_pi1.php',
	'tx_pnfcapdemat_pi1_wizicon' => $extensionPath . 'pi1/class.tx_pnfcapdemat_pi1_wizicon.php',
);
?>